### ISSUE TITLE
Boilerplate available?

### ISSUE THREAD

**Issue by ujwal-setlur** [cult-of-coders/apollo#21]
Hi,

Is there a boilerplate available for this package by any chance? I am currently referencing the [grapher-boilerplate](https://github.com/cult-of-coders/grapher-boilerplate), but just checking if is there is an updated boilerplate that includes cult-of-coders/apollo.

Thanks,

-ujwal

**Comment by theodorDiaconu** [comment]
https://github.com/theodorDiaconu/grapher-performance
