### ISSUE TITLE
Use DDP?

### ISSUE THREAD

**Issue by mattblackdev** [cult-of-coders/apollo#22]
@theodorDiaconu Is it not possible to leverage the DDP connection like swydo:ddp-apollo? Or are there good reasons not to?

**Comment by theodorDiaconu** [comment]
@mattblackdev there are good reasons not to. I'd use swydo:ddp-apollo when I would like to migrate my existing meteor app incrementally, otherwise I'd rather use plain websocket. DDP adds extra layers of complexity over websocket communication.
