### ISSUE TITLE
Unsure how to use apollo-live-client for live subscriptions

### ISSUE THREAD

**Issue by ujwal-setlur** [cult-of-coders/apollo#23]
Hi,

I have a subscription going with apollo-live-server which I can test with GraphiQL:

```
subscription {
  groups {
    event
    doc {
      _id
      name
    }
  }
}
```

However, it is not clear how to use the apollo-live-client. I am using it in a react-native environment. I have set up the websocket link correctly, I believe:

```
// our websocket link for subscriptions
const wsLink = new WebSocketLink({
  uri: constants.GRAPHQL_SUBSCRIPTION_ENDPOINT,
  options: {
    reconnect: true,
    connectionParams: () => ({
      [constants.AUTH_TOKEN_KEY]: getLoginToken() // this is asynchronous
    })
  }
});

// concat our link for a subscription link which uses websocket
const subscriptionLink = ApolloLink.from([errorLink, wsLink]);

// now use split to choose the correct link for subscription vs method
const link = split(({query}) => {
  const {kind, operation} = getMainDefinition(query);
  return kind === "OperationDefinition" && operation === "subscription";
}, subscriptionLink, methodLink);
```

Regular queries work fine, but I haven't gotten subscriptions to work yet. Here is what I am using. I am sure it's wrong. Any help will be appreciated:

```
const GET_GROUPS = gql`
  query {
    groups {
      _id
      name
    }
  }
`;

const SUBSCRIBE_GROUPS = gql`
  subscription {
    groups {
      event
      doc {
        _id
        name
      }
    }
  }
`;

  render() {
    return (
      <Container>
        <Content>
          <ReactiveQuery
            query={GET_GROUPS}
            subscription={SUBSCRIBE_GROUPS}
          >
            {({data: {groups}, loading, error}) => {
               if (loading) return <Text>
                                     Loading
                                   </Text>;
               if (error) return <Text>
                                   {error}
                                 </Text>;
             
               return <Text>
                        {JSON.stringify(groups)}
                      </Text>;
             }}
          </ReactiveQuery>
        </Content>
      </Container>
      );
  }
```

What gets rendered is the just the query results, but I don't see the subscription updates coming in.

How do I debug this?

Thanks!

**Comment by ujwal-setlur** [comment]
OK, the subscription request doesn't even seem to be getting to the server...need to debug that...

**Comment by ujwal-setlur** [comment]
It seems the websocket connection to the server is closing immediately. I tried command line utilities like wsc and wscat to connect to ws://localhost:3000/subscriptions. 

```
wscat -c ws://localhost:3000/subscriptions                                                                                                         ✘ 255 feature/infrastructure ✚ ✱
connected (press CTRL+C to quit)
disconnected
```

```
wsc ws://localhost:3000/subscriptions                                                                                                                    feature/infrastructure ✚ ✱
Connected to ws://localhost:3000/subscriptions
> Connection closed
```

But GraphiQL can connect via browser. Doesn't GraphiQL also use websockets for subscriptions?

**Comment by ujwal-setlur** [comment]
Actually, I don't think the websocket issue is the problem. I used react-native-websocket to open a websocket from within my app to ws://localhost:3000/subscriptions, and it worked. A socket is created and opened and does not immediately close. 

However, the subscription request does not reach the subscription resolver on the server, so either there is a problem with the WebSocketLink or with the subscription query.

**Comment by theodorDiaconu** [comment]
@ujwal-setlur I would first advise you to test a barebones subscription, without `apollo-live-client` to make sure it works properly. Maybe there are certain security rules that prevent websocket connections ?

**Comment by theodorDiaconu** [comment]
@ujwal-setlur to make sure this works, can you run your subscription in GraphiQL ? It should work automatically. If all works there I think the problem may be on RN side

**Comment by ujwal-setlur** [comment]
@theodorDiaconu, actually I tried that. That is not working either, My app actually crashed when I tried something like this:

```
const observable = client.subscribe({ query: SUBSCRIBE_GROUPS });
const subscription = observable.subscribe({ <--- this crashed the app
  next({ data }) {
    // data is your payload
    // do something with it
  },
});
```

Continuing to debug...

**Comment by ujwal-setlur** [comment]
@theodorDiaconu, yes, as I said in the initial problem report, subscription via GraphiQL works so the server side is set up fine, I believe.

**Comment by theodorDiaconu** [comment]
@ujwal-setlur In that case there's something going on at RN level... something acting up with the client, what is the error ? why is your app crashing ?

**Comment by ujwal-setlur** [comment]
Will post the code and error in a few mins

**Comment by ujwal-setlur** [comment]
Actually, the code is not crashing anymore. Maybe I had it in the wrong place before. This is what I have in my component:

```
export default class MyComponent extends Component {
  constructor(props) {
    super(props);
  }

  componentDidMount() {
    this.subscribeGroups();
  }

  subscribeGroups() {
    console.log("subscribing groups");
    const observable = this.props.client.subscribe({
      query: SUBSCRIBE_GROUPS
    });
    const subscription = observable.subscribe({
      next({data}) {
        console.log("got data");
        // data is your payload
        // do something with it
      }
    });
  }

  render() {
    return (
      <Container>
        <Content>
          <ReactiveQuery
            query={GET_GROUPS}
            subscription={SUBSCRIBE_GROUPS}
          >
            {({data, loading, error}) => {
               if (loading) return <Text>
                                     Loading
                                   </Text>;
               if (error) return <Text>
                                   {error}
                                 </Text>;
             
               return <Text>
                        {JSON.stringify(data)}
                      </Text>;
             }}
          </ReactiveQuery>
        </Content>
      </Container>
      );
  }
}
```

The code does not crash, but I don't see the subscription reaching the server side. It makes me think the ws link is not set up right?

**Comment by ujwal-setlur** [comment]
This is the crash I got on iOS. I got it before on Android as well, but then it went away. Very confusing...

<img width="377" alt="screen shot 2018-05-21 at 11 02 46 pm" src="https://user-images.githubusercontent.com/5835869/40344758-1d8c90ce-5d4b-11e8-97e1-7f9e8a1265a8.png">

**Comment by theodorDiaconu** [comment]
Show me your typeDefs, how you define this server-side, and also the resolvers

**Comment by ujwal-setlur** [comment]
OK, I identified the culprit! I was setting an option for the Meteor auth token in the WebSocketLink, but it was with an asynchronous call:

```
const wsLink = new WebSocketLink({
  uri: constants.GRAPHQL_SUBSCRIPTION_ENDPOINT,
  options: {
    reconnect: true,
    connectionParams: () => ({
      [constants.AUTH_TOKEN_KEY]: getLoginToken() // <-- This asynchronous call caused the problem!
    })
  }
});
```

I had patched subscriptions-trasnport-ws to allow for async calls to set header per https://github.com/apollographql/subscriptions-transport-ws/pull/348, but clearly this is not working. When I just use:

```
const wsLink = new WebSocketLink({
  uri: constants.GRAPHQL_SUBSCRIPTION_ENDPOINT,
  options: {
    reconnect: true
  }
});
```

then things work! I will have to figure out another way of setting the async auth header.

Thanks for the help!

**Comment by theodorDiaconu** [comment]
@ujwal-setlur here you go:
```js
import { AsyncStorage } from 'react-native'
import ApolloClient from 'apollo-client'
import { HttpLink } from 'apollo-link-http'
import { setContext } from 'apollo-link-context'
import { InMemoryCache } from 'apollo-cache-inmemory'
import {
  from,
} from 'apollo-client-preset'

export function initialize() {
  const httpLink = new HttpLink({
    uri: 'http://192.168.1.146:3000/graphql',
  })

  const authMiddleware = setContext(() =>
    AsyncStorage.getItem('Meteor.loginToken').then(loginToken => ({
      headers: {
        'meteor-login-token': loginToken,
      },
    })))

  const client = new ApolloClient({
    link: from([authMiddleware, httpLink]),
    cache: new InMemoryCache({
      dataIdFromObject: object => object._id || null,
    }),
  })

  return client
}
```

**Comment by theodorDiaconu** [comment]
Sorry, I now realise that this approach wouldn't work for Websockets, but I think with websockets the logic is that you can use getLoginToken() that reads from somewhere, and when that something changes, just reconnect. And problem solved. Also if you do solve this, would you be kind enough to submit a PR updating docs in here ? If not just leave the solution here so others won't head into this issue.

**Comment by ujwal-setlur** [comment]
@theodorDiaconu, will do! Thanks a lot for your help and attention!

**Comment by ujwal-setlur** [comment]
@theodorDiaconu, this works for me:

```
const wsLink = new WebSocketLink({
  uri: constants.GRAPHQL_SUBSCRIPTION_ENDPOINT,
  options: {
    reconnect: true,
    connectionParams: () => ( // a promise that resolves to return the loginToken
    new Promise((resolve, reject) => { // eslint-disable-line no-undef,no-unused-vars
      getLoginToken().then(token => {
        if (token) {
          resolve({
            [constants.AUTH_TOKEN_KEY]: token
          });
        } else {
          resolve({
            [constants.AUTH_TOKEN_KEY]: ""
          });
        }
      });
    })
    )
  }
});
```

**Comment by ujwal-setlur** [comment]
When login token changes, reset the websocket connection:

```
wsLink.subscriptionClient.close(true, true);
wsLink.subscriptionClient.tryReconnect();
```

at the appropriate place.

**Comment by ujwal-setlur** [comment]
I will open a documentation PR soon.

**Comment by ujwal-setlur** [comment]
All issues reported here have been resolved. None of them were issues with this package. Closing.
