### ISSUE TITLE
Shift to Apollo Server 2.0 and use checkNpmVersions

### ISSUE THREAD

**Issue by theodorDiaconu** [cult-of-coders/apollo#27]
https://github.com/apollographql/apollo-server/issues/1172#issuecomment-397974075

**Comment by mattblackdev** [comment]
I couldn't figure out how to connect WebApp with 2.0. I tried a few variations and gave up pretty quick since it's beta anyway. I think it has something to do with the built-in http server in 2.0.

**Comment by theodorDiaconu** [comment]
@mattblackdev that would be bad, unless meteor would have a way to start without it's http server. But I'm sure they would still want to be able to apply themselves to express() or others. 

I think there should be a way for this: https://www.apollographql.com/docs/apollo-server/v2/essentials/server.html#middleware

**Comment by mattblackdev** [comment]
How would you obtain a reference to the express app?
```
registerServer({ server, app }); // app is from an existing express app
```
This is exactly what I tried but I don't think I figured out the right "app" reference.

**Comment by mattblackdev** [comment]
Haven't tested yet myself, but apparently there is a newer version not yet referenced in the docs:
```
apollo-server-express@rc
```
From @evans' [comment](https://github.com/apollographql/apollo-server/issues/1172#issuecomment-397974075):
> "[...] with apollo-server-express rc, you can import the ApolloServer class without the dependency on apollo-sever"

And to answer my own question about ```WebApp```, use ```connectHandlers```.

I'm guessing it goes something like:
```
import { ApolloServer } from 'apollo-server-express'
import { WebApp } from 'meteor/webapp'

const server = new ApolloServer()
server.applyMiddleware({
  app: WebApp.connectHandlers,
  server,
  path: '/graphql'
})
```

**Comment by theodorDiaconu** [comment]
That is excellent. I'm waiting for the release but this looks promising, we're gonna remove a bunch of npm dependencies!

**Comment by StorytellerCZ** [comment]
Looks like it is out: https://blog.apollographql.com/announcing-apollo-server-2-2b69fb4702ce

**Comment by lorensr** [comment]
`server.applyMiddleware({ app: WebApp.connectHandlers,`

Were you able to get this working? I'm getting a `Error: Can't set headers after they are sent.` error:

https://github.com/apollographql/meteor-integration/issues/123#issuecomment-406768233

**Comment by theodorDiaconu** [comment]
@lorensr yes, I know the error. Just add this:

```
  // We are doing this work-around because Playground sets headers and WebApp also sets headers
  // Resulting into a conflict and a server side exception of "Headers already sent"
  WebApp.connectHandlers.use('/graphql', (req, res) => {
    if (req.method === 'GET') {
      res.end();
    }
  });
```
