### ISSUE TITLE
New version doesn't support websocket for DDP?

### ISSUE THREAD

**Issue by goodideal** [cult-of-coders/apollo#43]
I found `DISABLE_SUBSCRIPTIONS` was removed from settings.

**Comment by theodorDiaconu** [comment]
@goodideal yes, so the story with apollo-server-2 now is that if you don't have any `type Subscription` it doesn't open the websocket, just by adding the Subscription it does this automatically for you. So... we currently provide no way of doing so, just don't load any subscription types.
