### ISSUE TITLE
inverse links question

### ISSUE THREAD

**Issue by ericmcgregor** [cult-of-coders/apollo#48]
I'm having trouble getting inverse links to function.  I keep getting the fields returned as null.  I have everything setup properly, and the data is being returned properly the other way.

type Counter @mongo(name: "counters") {
  _id: ID!
  count: Float
  userId: ID!
  user: User @link(field: "userId")
}

type User @mongo(name: "users") {
  _id: ID!
  counter: Counter @link(to: "user")
}

I imagine that it should just work both ways?  or am i mistaken?  My "Counter" query will return any information from User that i want.  but if i try to return the count in my User query, i get null.

Also, does this automatically map the field specified in the first collection to the _id in the second?

**Comment by theodorDiaconu** [comment]
@ericmcgregor it should work out of the box, need more details on this one.

**Comment by ujwal-setlur** [comment]
There were some inverse link issues before that got resolved. Best to supply a sample repo to debug.
