### ISSUE TITLE
allow to override `"resolveUser"` in `getUserContext`

### ISSUE THREAD

**Issue by smeijer** [cult-of-coders/apollo#49]
The current user is resolved by a `Meteor.users.findOne`. Works perfectly. Although, I would like to replace this with a `Meteor.users.rawCollection().findAndModify` to keep track of user activity;

```js
Meteor.users.rawCollection().findAndModify(
  { _id: userId },
  {},
  { $set: { lastSeen: new Date() } },
  { new: true },
);
```

https://github.com/cult-of-coders/apollo/blob/307bc8f1c51356b8208b55f81d93e332ec9b92c3/server/core/users.js#L24-L34

What's your opinion on this? Are you open for this change? And if you are, in what way?

Options that come to my mind:

**Add simple `initialize` setting:** 

```js
initialize({}, {
  trackUserLastSeen: true,
  userFields: {
    _id: 1,
    roles: 1,
  }
}),
```

**Add `resolveUser` function**
```js
initialize({}, {
  resolveUser: (token, fields) => Meteor.users.rawCollection().findAndModify(..)
}),

// /server/core/users
const currentUser = typeof resolveUser === 'function' 
  ? resolveUser(token) 
  : Meteor.users.findOne(...)
```

First option benefits from easy config. One of the selling points of this library. The second one provides better decoupling from database / meteor. But that doesn't seem to be one of the goals for this library.

**Comment by theodorDiaconu** [comment]
Sounds like a good feature. Will do.

**Comment by smeijer** [comment]
Is this already possible? I have a similar need, for a different implementation.

In my current case, my users aren't stored in the `db.users` collection, and thereby I need to implement a completely different user resolver. 

This is both required for the `resolvers` as well as the `subscriptions`.

**Comment by theodorDiaconu** [comment]
@smeijer feel free to make a PR

**Comment by smeijer** [comment]
@theodorDiaconu, thanks. Done.

A different approach than I was thinking about when opening this issue. But I think it's way more flexible this way.
