### ISSUE TITLE
Upgrading to Meteor 1.8 changes behavior of adding the user object to Apollo's context object

### ISSUE THREAD

**Issue by yellowspaceboots** [cult-of-coders/apollo#55]
When I upgraded my meteor application from 1.7 to 1.8 the user object on my Apollo context lost the "profile" object containing the user's name and other profile information. The _id is still added to context and so as a work around I just called Meteor.users.findOne(context.user._id) to get the rest of the information and that works so far but I just wanted to bring it up here. I am not sure why this upgrade would drop only a part of the user object and perhaps it has to do with my accounts set up but it was working fine in 1.7 and then 1.8 the only errors I received had to do with missing information in the user object. Once I implemented the above work around all works as expected.

**Comment by theodorDiaconu** [comment]
https://github.com/cult-of-coders/apollo/blob/master/docs/settings.md

Look at the userFields. Did you update those properly ?
