### ISSUE TITLE
Ability to apply configs to ApolloClient constructor

### ISSUE THREAD

**Issue by jaxtisapia** [cult-of-coders/apollo#58]
On calling `intialise` to retrieve client object,
creation of the original  ApolloClient is limited.

For instance, applying a config like `  addTypename: false` becomes impossible;

Below is the exact code-snippet that intialises and returns the client object

```
  const client = new ApolloClient({
    link: terminatingLink,
    cache: new InMemoryCache({
      dataIdFromObject: object => object._id || null,
    }).restore(window.__APOLLO_STATE__ || {}),
  });

  return {
    client,
  };
```

**Comment by theodorDiaconu** [comment]
For anything custom, you can create your own apollo object. This is meant to be extremely simple solution to just make it work.
