### ISSUE TITLE
[Question] Fields resolved by external API

### ISSUE THREAD

**Issue by mattblackdev** [cult-of-coders/apollo#61]
@theodorDiaconu what's your recommendation for resolving some fields via external API's?

I thought of 2 ways:
1. Use grapher's Collection.AddReducers
```
Businesses.addReducers({
  ratingAndReviews: {
    body: { googlePlaceId: 1 },
    reduce({ googlePlaceId }) {
      const wrappedGetPlaceDetails = Meteor.wrapAsync(getPlaceDetails)
      const { rating, reviews } = wrappedGetPlaceDetails(googlePlaceId)
      return { rating, reviews }
    },
  },
})
```
The nice thing is you only need to write this once and it's pretty clean. But, it seems like you lose a little flexibility, for example ratingAndReviews is an object type when it should be two fields: rating and reviews. 

2. In the graphql resolver, check the query body and fetch if needed (not sure if this would even work)
```
businesses: async (_, args, ctx, ast) => {
  const query = ctx.db.businesses.astToQuery(ast, {
    embody({ body }) {
      if (body.rating || body.reviews) {
        body.googlePlaceId = 1
      }
    }
  })
  let docs = query.fetch()
  if (body.rating || body.reviews) {
    docs = await Promise.all(docs.map(async doc => {
      const { rating, reviews } = await getPlaceDetails(doc.googlePlaceId)
      return { ...doc, rating, reviews }
    }))
  }
  return docs
},
```
This seems pretty nasty and it would be different for fetchOne(), but allows for resolving fields flatly.

I feel like neither of these is the "right" way so I'm wondering if I've missed something?

Thanks for your help!

**Comment by mattblackdev** [comment]
Here's a bit of the schema to give more context:

```
type Business @mongo(name: "businesses") {
  _id: ID!
  name: String!
  address: Address!
  googlePlaceId: String!
  reviewDetails: ReviewDetails!
}

type ReviewDetails {
  rating: Int
  reviews: [Review]
}

type Review {
  author_name: String
  rating: Int!
  text: String
  time: Int!
}
```

I liked using AddReducers as well but I wished for a couple things. In the example, I changed the ```reviewDetails``` field name to ```ratingAndReviews``` to make a point. From a design perspective, the ```rating``` and ```reviews``` fields don't need to be nested, but only because the alternative would be to have two reducers calling the same api twice just to resolve both fields. Now that I think about it, I could memoize that api request and it would be fine, but I would need some kind of request Id variable:
```
Businesses.addReducers({
  rating: {
    body: { googlePlaceId: 1 },
    reduce({ googlePlaceId }, { requestId }) {
      const { rating } = wrappedAndMemoizedGetPlaceDetails(googlePlaceId, requestId)
      return rating
    },
  },
  reviews: {
    body: { googlePlaceId: 1 },
    reduce({ googlePlaceId }, { requestId }) {
      const { reviews } = wrappedAndMemoizedGetPlaceDetails(googlePlaceId, requestId)
      return reviews
    },
  },
})

// then in the resolver pass request Id through via query params...
businesses: async (_, args, ctx, ast) => {
  const query = ctx.db.businesses.astToQuery(ast)
  query.params({ requestId: ctx.requestId })
  return query.fetch()
},
```

The other thing I wished for was async/await in ```reduce```. But that's just a personal preference I think, because I like all my api calls to return promises. I had to refactor the ```getPlaceDetails``` google api call to be in callback form to use Meteor.wrapAsync(), which I've never dealt with before. Not sure if there's any other way to do that.

**Comment by mattblackdev** [comment]
Okay so further thinking on this, it would seem I could use [data-loader](https://github.com/facebook/dataloader) to deal with the multiple requests and memoizing.

**Comment by theodorDiaconu** [comment]
Data-loader would be good for caching redundant requests.

**Comment by theodorDiaconu** [comment]
Is this issue resolved ?

**Comment by mattblackdev** [comment]
Is the solution we arrived at worth documenting?
