### ISSUE TITLE
me query returns null

### ISSUE THREAD

**Issue by 1337cookie** [cult-of-coders/apollo#62]
Trying the example on https://github.com/cult-of-coders/apollo/blob/master/docs/accounts.md
when I run the me query after creating a user and logging in.
`query{
 me{
  _id
 }
}`
it returns null for the _id. I console logged the context object in the resolver and it returns

`{ db: {},
  user: {},
  userId: null,`

what am I missing or what is missing in the example?

Edit: After posting this I realised I have installed graphql playground which doesn't have authentication support IIRC?

**Comment by theodorDiaconu** [comment]
@1337cookie you have to go to http headers, and use meteor-login-token

**Comment by ajaybhatia** [comment]
It's not working. Always getting { db: {}, user: {}, userId: null, ... even on setting http-header with { "authorization": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" }

**Comment by srpf** [comment]
@theodorDiaconu I have this problem, on meteor v.1.8
Do you have a sample solution?

**Comment by theodorDiaconu** [comment]
@srpf show me a reproduction. I don't have it.

**Comment by srpf** [comment]
> @1337cookie you have to go to http headers, and use meteor-login-token

How to go http headers and use meteor-login-token

After load AccountsModule `load(AccountsModule);` I run the me query `query{ me{ _id } }` resolver returns context.userId of null `{ db: {}, user: {}, userId: null }`

**Comment by theodorDiaconu** [comment]
Http headers from GraphQL Playground. Token received from login/register mutations

Regards,
Theodor

**Comment by srpf** [comment]
@theodorDiaconu  Ok thank, it work for me
