### ISSUE TITLE
[Question] How to expose links' metadata in schema

### ISSUE THREAD

**Issue by mattblackdev** [cult-of-coders/apollo#64]
Suppose I have the following schema:

```
type Party @mongo(name: "parties") {
  _id: ID!
  name: String!
  users: [User] @link(field: "userLinks" metadata: true)
}

type User @mongo(name: "users") {
  _id: ID!
  username: String!
  parties:  [Party] @link(to: "users")
}

type Query {
  party(_id: ID!): Party
}
```
And ```userLinks``` looks like:
```
[
  {
    "_id": "1",
    "role": "LEADER"
  },
  {
    "_id": "2",
    "role": "MEMBER"
  }
]
```

The client can query:
```
query PartyUsers($_id: ID!) {
  party(_id: $_id) {
    _id
    users {
      _id
      username
    }
  }
}
```

But how would the client be able to know what role each user has?

**Comment by theodorDiaconu** [comment]
We don't recommend using $metadata anymore, this is why it hasn't been enabled. Grapher is already very performant, and initially meta links were designed for that. 
A solution would be to rewrite the $metadata link to a field compatible name like __metadata or something.
